language:
  - c
  - cpp

compiler:
  - gcc

os:
  - linux

install:
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo apt-get install libpqxx-dev
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
  - wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
  - tar xfz boost_1_72_0.tar.gz
  - rm boost_1_72_0.tar.gz
  - cd boost_1_72_0
  - ./bootstrap.sh --prefix=/usr --with-python=python3 && ./b2 -d0 stage -j4 threading=multi link=shared
  - sudo ./b2 -d0 install threading=multi link=shared   
  - cd -
  - sudo apt-get install google-mock
  - cd /usr/src/gmock
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
  - sudo apt update
  - sudo apt install postgresql postgresql-contrib -y
  - sudo -i -u postgres
  - sudo -u postgres createuser --interactive
  - sudo -u postgres createdb comred
  - sudo cp -f ./scripts.sql /var/lib/postgresql/scripts.sql
  - sudo -i -u postgres
  - sudo psql -U postgres -d comred -a -f scripts.sql

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - ./ServerApplication/test_usecase
  - ./DB/test_repo
  - ./HTTPServer/test_e2e

after_script:
  - make clean